steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config --global init.defaultBranch main
      git init

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - DesdeGit
    - --source=gs://downloadBase/function-source.zip
    - --trigger-http
    - --entry-point=main
    - --runtime=python38
    - --allow-unauthenticated

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - call
    - DesdeGit


    
# artifacts:
#   objects:
#     location: 'gs://gcf-v2-sources-41404494176-us-central1/downloadBase/'
#     paths: ['*.zip']
