steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config --global init.defaultBranch main
      git init

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - gatillador
    - --source=.
    - --trigger-http
    - --runtime=python38
    - --allow-unauthenticated
